### ISSUE TITLE
Inquiry About Test Set Answers

### ISSUE THREAD

**Issue by YuqiHUO** [II-Bench/II-Bench#1]
Hello,

Firstly, I would like to express my gratitude for sharing this benchmark. It is an excellent piece of work.

I am writing to inquire about the answers for the test set. Could you please let me know where I can find them? Additionally, I would appreciate any guidance on how to evaluate my model's performance on the test set.

Thank you very much for your assistance.

**Comment by icoderzqliu** [comment]
Thank you for your interest in our work. We will open the submission channel for test answers soon.

**Comment by icoderzqliu** [comment]
> Hello,
> 
> Firstly, I would like to express my gratitude for sharing this benchmark. It is an excellent piece of work.
> 
> I am writing to inquire about the answers for the test set. Could you please let me know where I can find them? Additionally, I would appreciate any guidance on how to evaluate my model's performance on the test set.
> 
> Thank you very much for your assistance.

Hello,

We have released [II-Bench](https://eval.ai/web/challenges/challenge-page/2334/overview) challenge on EvalAI. You can submit your results and evaluate them there. You can refer to our [GitHub](https://github.com/II-Bench/II-Bench) to run your inference, use [none.yaml](https://github.com/II-Bench/II-Bench/blob/main/config/none.yaml) as the default prompt template, and use [eval.py](https://github.com/II-Bench/II-Bench/blob/main/eval.py) to extract answers from the inference results.
